version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass

#version: '3.8'
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-deadline
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_RANDOM_ROOT_PASSWORD: yes
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: test_user
#      MYSQL_PASSWORD: test_password
#    volumes:
#      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
#    restart: always